### ISSUE TITLE
API stopped working on 5/17?

### ISSUE THREAD

**Issue by kscomtb** [kk7ds/gaiagpsclient#10]
My script that syncs gaia tracks with strava stopped working yesterday afternoon.  My account seems to be in good standing as browser access to gaiagps.com is still working as expected.  A quick test using the command-line tool shows the following:

```
$ gaiagps --user XXXXXXXXX@gmail.com --verbose test
Password:
INFO:gaiagps.apiclient:Login successful
Unable to access gaia
$
```

It appears that the login is successful, but it fails after that.  

Other command-line tests produce the following stack trace, which is the same stack trace my script produces: 

```
$ gaiagps --user XXXXXXXX@gmail.com --verbose track list      
Password:
INFO:gaiagps.apiclient:Login successful
Traceback (most recent call last):
  File "/usr/local/bin/gaiagps", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/gaiagps/shell/__init__.py", line 102, in main
    return int(cmd.dispatch(parser, args) or 0)
  File "/usr/local/lib/python3.8/dist-packages/gaiagps/shell/command.py", line 67, in dispatch
    return getattr(self, fn_name)(args)
  File "/usr/local/lib/python3.8/dist-packages/gaiagps/shell/command.py", line 281, in list
    items = self.client.list_objects(objtype, archived=show_archived)
  File "/usr/local/lib/python3.8/dist-packages/gaiagps/apiclient.py", line 178, in list_objects
    return r.json()
  File "/usr/lib/python3/dist-packages/requests/models.py", line 897, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3/dist-packages/simplejson/__init__.py", line 518, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3/dist-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/usr/lib/python3/dist-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
$
```

Did something change on the back end to break the API, or is it an issue with my gaia account?  Anyone else having problems?

**Comment by cboone** [comment]
Same problem here, and I see the same output with the commands that @kscomtb lists.

Also, my script assumes that the user has logged in already using `gaiagps --user <EMAIL> test`, so when it runs `gaiagps --verbose track list` the output is:

```
Unable to access Gaia: Session expired; username and password are required
```

**Comment by cboone** [comment]
Running `gaiagps --debug --user <EMAIL> test` I get a more detailed failure:

```
reply: 'HTTP/1.1 504 Gateway Time-out\r\n'
header: Content-Type: text/html
header: Content-Length: 1033
header: Connection: keep-alive
header: Server: CloudFront
header: Date: Fri, 19 May 2023 00:35:40 GMT
header: X-Cache: Error from cloudfront
header: Via: 1.1 1a25e657bbdfbe4dde177fef28655f02.cloudfront.net (CloudFront)
header: X-Amz-Cf-Pop: EWR52-C4
header: Alt-Svc: h3=":443"; ma=86400
header: X-Amz-Cf-Id: gpk5iHmgP0kTqpN4BugZ_jRBRuSdz-e6rrBQ4Zhf8s2cp38kY870kQ==
DEBUG:urllib3.connectionpool:https://www.gaiagps.com:443 "POST /register/addDevice/ HTTP/1.1" 504 1033
DEBUG:gaiagps.apiclient:Status code from login was 504
Unable to access Gaia: Login failed
```

**Comment by cboone** [comment]
When I run `gaiagps --debug --user <EMAIL> test`, I see a reasonable sequence of requests and responses. But even though the post to `/register/addDevice/` returns 200 from the server, the subsequent calls reveal that authentication has not successfully occurred. In other words, https://github.com/kk7ds/gaiagpsclient/blob/e1643daf3eb326f8d3263b962faff8214471187b/gaiagps/apiclient.py#L124 returns false.

**Comment by cboone** [comment]
I just took a look at how the web app performs authentication, and the overall flow seems the same as what's here.

The only difference that stands out to me is all the cookie keys and values that the web app passes but the CLI doesn't. I'm not at all familiar with this code base or this API (other than from using this awesome CLI, thanks @kk7ds!), so I'm guessing pretty ignorantly, but maybe the API now expects a value that the CLI isn't providing?

**Comment by kk7ds** [comment]
Maybe we can get a hint from @jessecrocker ?

**Comment by JesseCrocker** [comment]
Sorry, I no longer work there.Sent from my iPhoneOn May 18, 2023, at 7:05 PM, Dan Smith ***@***.***> wrote:﻿
Maybe we can get a hint from @JesseCrocker ?

**Comment by msaxer** [comment]
Any luck tracking down the cause of, and possible fix for, this issue? I'm a first time user of the CLI package and was confused by what I was seeing in the --debug output. Thankfully the initial bug report matches exactly what I'm seeing (albeit on Windows rather than a *nix environment).

**Comment by lewisthompson** [comment]
The text body response from `/register/addDevice` is

```
{"code":1080,"message":{"recaptcha":["This field may not be null."]}}
```

**Comment by redfern314** [comment]
Looks like Gaia added a reCaptcha v2 ([invisible](https://developers.google.com/recaptcha/docs/invisible)) to the login process. I don't know if there's a good way around it, even with a human in the loop, as reCaptcha is meant to prevent this kind of scraping. Luckily, it looks like it's only for the login screen; after that, the cookies used are valid in the Python library too.

I was able to work around it by signing in with a browser, then copy/pasting the sessionid cookie into `~/.gaiagpsclient` as a new cookie field. It looks like the cookie is valid for 2 weeks, after which I'll need to do that again.

One short-term mitigation might be to add a `--session-id` parameter to the CLI, to make it a bit more user-friendly to pass it in... but it still relies on users going into their browser and dredging up the cookie value.

**Comment by kk7ds** [comment]
Cool, if that works it should be fairly easy to do.

**Comment by zefoo** [comment]
Does that mean we'd need to manually log into Gaia web UI every 2 weeks to pull cookies, if I'm following? 

Does Gaia have a web UI we can use that this point if this library is no longer functionality like it was?

**Comment by kk7ds** [comment]
It might stay fresh if you keep using it, but I dunno.

When I started this project it got a little attention from the gaia people at the time. It sounded like there was some potential for a future app registration sort of interface to enable us to use the API, but I don't think that ever materialized. This tool is using the same API that the app and the web UI uses, FWIW.

**Comment by kk7ds** [comment]
Also note that trailsoffroad and gaia are owned by the same parent company (outdoor) so seeing integrations is not surprising :)

**Comment by zefoo** [comment]
Oh! Of course. I wonder how the Gaia iOS app does the captcha or if they have a way around that. 🤔 I could see about watching traffic sometime if we haven't explored that. It's also possible with his website is the only route. 

Appreciate all your efforts to get this going! I know Outside has changed some things over there. I still haven't touched OnX... I'm loyal to Gaia. 😅

**Comment by kk7ds** [comment]
Clearly they have their own authentication mechanism for their app. Even before they (intentionally) broke the web auth we were using, I'm sure they were using something else for themselves.

**Comment by redfern314** [comment]
Yeah, agreed - they must have a private integration mechanism. You could watch the traffic, but I don't think it would help this particular use case because you still have to log in using a browser when you connect the accounts in that way.

By the way, I saw several threads ([1](https://help.gaiagps.com/hc/en-us/community/posts/115006615847-Public-API-for-Automated-Uploading-of-Waypoint-Data-to-gaia-com), [2](https://help.gaiagps.com/hc/en-us/community/posts/360022075193-Strava-Integration)) on the Gaia feature request portal (one of which @kk7ds had commented on) and it just seems like a public API isn't a priority right now. Possibly because the Outside merger threw their engineering team for a loop: https://blog.gaiagps.com/type-2-engineeering/

**Comment by redfern314** [comment]
As mentioned in #11, I just checked to see if the session actually expired after 2 weeks like it said it would. Unfortunately, it did. Users will have to perform the refresh operation every 2 weeks until Gaia adds an officially supported mechanism.
