### ISSUE TITLE
Test login fails where as the UI on gaiagps.com does not.

### ISSUE THREAD

**Issue by laserguy2020** [kk7ds/gaiagpsclient#2]
root@695cf81ae7b1:/app# gaiagps --user '<<REDACTED>>' --debug test
DEBUG:parser:Arguments: Namespace(cmd='test', debug=True, pass_=None, user='<<REDACTED>>', verbose=False)
Password: <<REDACTED>>
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): www.gaiagps.com
send: b'GET /login/ HTTP/1.1\r\nHost: www.gaiagps.com\r\nAccept-Encoding: identity\r\nUser-Agent: https://github.com/kk7ds/gaiagpsclient (Python/3.6.9; linux; requests/2.18.4)\r\nAccept: application/json, text/plain, */*\r\n\r\n'
reply: 'HTTP/1.1 200 OK\r\n'
header: Content-Type: text/html; charset=utf-8
header: Content-Length: 38819
header: Connection: keep-alive
header: Date: Sun, 08 Mar 2020 16:06:42 GMT
header: Server: nginx
header: Cache-Control: max-age=3600
header: Content-Language: en
header: Vary: Accept-Encoding,Accept-Language,Cookie
header: X-Cache: Hit from cloudfront
header: Via: 1.1 15ce0329949ac28ffe4b40b091e277ef.cloudfront.net (CloudFront)
header: X-Amz-Cf-Pop: ORD51-C1
header: X-Amz-Cf-Id: ZEB7t64L6UW0FehqJ-nnuL5DrJ_QXi5XHQjA3lIYOtdr4WyaVISSyQ==
header: Age: 598
DEBUG:urllib3.connectionpool:https://www.gaiagps.com:443 "GET /login/ HTTP/1.1" 200 38819
DEBUG:gaiagps.apiclient:Not authenticated, logging in...
send: b'POST /login/ HTTP/1.1\r\nHost: www.gaiagps.com\r\nAccept-Encoding: identity\r\nUser-Agent: https://github.com/kk7ds/gaiagpsclient (Python/3.6.9; linux; requests/2.18.4)\r\nAccept: application/json, text/plain, */*\r\nContent-Length: 69\r\nContent-Type: application/x-www-form-urlencoded\r\n\r\n'
send: b'username=<<REDACTED>>&password=<<REDACTED>>&next=%2F'
reply: 'HTTP/1.1 200 OK\r\n'
header: Content-Type: text/html; charset=utf-8
header: Content-Length: 38819
header: Connection: keep-alive
header: Vary: Accept-Encoding
header: Date: Sun, 08 Mar 2020 16:16:40 GMT
header: Server: nginx
header: Cache-Control: max-age=3600
header: Vary: Accept-Encoding
header: Content-Language: en
header: X-Cache: Miss from cloudfront
header: Via: 1.1 15ce0329949ac28ffe4b40b091e277ef.cloudfront.net (CloudFront)
header: X-Amz-Cf-Pop: ORD51-C1
header: X-Amz-Cf-Id: hweysa5gGuQ2eFI4xjcPK3OTeQqy_JoDz4oR6THXu5o3_QggFXdblA==
DEBUG:urllib3.connectionpool:https://www.gaiagps.com:443 "POST /login/ HTTP/1.1" 200 38819
DEBUG:gaiagps.apiclient:Post login expected /, got https://www.gaiagps.com/login/
Unable to access Gaia: Login failed

**Comment by kk7ds** [comment]
Yep, I see the same thing. This must have just started happening because it worked a few weeks ago when I used it for something else. I'll try to track down what has changed about the login process on the server side.

**Comment by JesseCrocker** [comment]
Hi Folks,
Yes, we changed some things with how login works. The change should not be to hard for you to adapt to, but i would suggest that you just hold off for a week, and then I can send you information about to switch to doing oauth2 based authentication instead of username and password.

**Comment by kk7ds** [comment]
Okay thanks, I was just poking a little bit just now and see that at least a URL changed, but there's something else going on as well. Thanks a lot for being willing to share the details!

**Comment by laserguy2020** [comment]
Sounds good. By the way thank you for creating this tool. I use this to get my location from my Iridium Go on to Gaia so my wife can see where I am when I off-road.

**Comment by al-2020-wq** [comment]
@JesseCrocker and @kk7ds any luck?

**Comment by kk7ds** [comment]
@JesseCrocker ping? I'd really like to get this resolved. I haven't really tried reverse engineering the new mechanism because it'd be super nice to just have some guidelines, but I can dig into that if necessary. Thanks for any help you can provide!

**Comment by icycle77** [comment]
Just discovered this tool, big thanks @kk7ds ! Curious if you've received any updated auth instructions from the Gaia team? 

I was hoping to iterate over the year's tracks and generate some statistics. This client would not only be ideal for that but also the only way I can think of outside of visiting each track and exporting. The new map side panel for tracks, etc is nice, but multi-select operations are limited to toggle map visibility and delete. The `datasummary/tracks/` view allows only multi-select of <= a page of tracks (20) or all of them, and operations there are save to folder, toggle sync, and delete. Neither method offers bulk export.

Thanks again for your work on this.

**Comment by kk7ds** [comment]
Nope, unfortunately not. I too missed out on a bunch of organization with the tool this summer, but had lots of other stuff going on in the world to keep me distracted. I'd still definitely like to get this resolved without having to try to reverse engineer the browser process (again).

**Comment by JesseCrocker** [comment]
@kk7ds We are still working on a solution for people to be able to generate oauth credentials to use in third party app, I cant give a date when it will happen, but it will probably happen at some point. As a temporary solution, please email me at jesse at gaiagps.com and i'll generate credentials for you.

**Comment by kk7ds** [comment]
I've emailed @JesseCrocker a couple times since December and haven't gotten a response, but I'll be merging a PR in a sec that should resolve the acute problem at least.
