### ISSUE TITLE
Cannot validate the install on Mac OS 10.11

### ISSUE THREAD

**Issue by gecko2019** [kk7ds/gaiagpsclient#3]
Hi Dan, tried to install this very useful CLI on my Mac. Ran into a problem with ('pathvalidate').

Fails on the final step listed here for the Mac install:
https://gaiagpsclient.readthedocs.io/en/latest/cookbook.html#colorize-tracks

$ python3 setup.py install
...
No local packages or working download links found for pathvalidate
error: Could not find suitable distribution for Requirement.parse('pathvalidate')

Please advise ! You may email me directly at gm.amos at gmail dot com

Thanks

**Comment by kk7ds** [comment]
I'll take a look at that, but at the moment we're waiting on gaiagps to provide us some details on their new authentication mechanism. See issue #2 for details. Once that is resolved, I'll take a look at what python package broke :)

**Comment by kk7ds** [comment]
I wonder if you need pip installed but don't have it? What happens if you try this:

```python3 -mpip install pathvalidate```

?
