### ISSUE TITLE
Question on --colorize

### ISSUE THREAD

**Issue by binarylandscapes** [kk7ds/gaiagpsclient#5]
Hello, you give an example of using the color data in a gpx file extensions to colorize meatching tracks that have been imported but will this work with KML/KMZ files that have the color data as an 8 character code not 6 that gaia is expecting? Right now importing said KML/KMZ file randomizes the colors

**Comment by kk7ds** [comment]
No, this is specific to gpx at the moment, but should be doable (within gaia's constraints) with a KML I think. If you'll post a KML example, I can see if it's easy to add.
