### ISSUE TITLE
Track ids that are 40 characters are not recognized by track show

### ISSUE THREAD

**Issue by rssllptrs** [kk7ds/gaiagpsclient#7]
Many of my gaiagps track ID's are both 36 and 40 characters long. The track show command will not show the ones that are 40 characters long with this error:
Item with title=6505ccef3cfffd6229e71f1528650b9edf8bfb47 not found
I was able to fix the issue by changing line 612 in utils.py from:
return (len(idstr) in (36, 32) and
to:
return (len(idstr) in (36, 32, 40) and

**Comment by kk7ds** [comment]
Sorry, I didn't notice this earlier when you posted it. Can you tell which client was used to create objects with 40-character IDs? I know the iOS and web clients seem to be responsible for the 32 and 36-character IDs. Android perhaps?

**Comment by rssllptrs** [comment]
Hi Dan,

It was the android app.

-Russ

**Comment by kk7ds** [comment]
Cool, that makes sense so glad to have the confirmation. No idea why gaia on all platforms doesn't use a standard model but oh well.

Thanks!
